name: Auto Deploy on Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Vercel
      run: |
        npm install -g vercel
        yes | vercel --confirm --token ${{ secrets.VERCEL_TOKEN }} --prod
